# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a20aef6fbe605d87cbd3083dbd1058274281a4aac0959751c7599b72a3464464007be03a2d382fa514045b9d3e9c383f4ffd1403e8661f31b9063e4e41286255

test:
  secret_key_base: 03e46797eea24a64571b4e31ff12ae5ada78764d5a71948d0dbabad9383d1e740dcc2a2a1ecd7ea888f989b31b1a72c1623a70cbca2ee42e680a411a8989e583

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
